version: "3.7"

## Media services for a home server
## Will Fantom

##REMEMBER! sonarr and radarr need "mkdir data && ln -s /downloads /data/completed" to fix directories 

services:
  # Manage all the following services with Organizr
  organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    restart: always
    ports:
      - 37010:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/organizr/config:/config
      - ${SHARED_DIR}:/shared

  # Download torrents (hidden behind a VPN provider)
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 37011:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - OPENVPN_PROVIDER=${VPNPROVIDER}
      - OPENVPN_USERNAME=${VPNEMAIL}
      - OPENVPN_PASSWORD=${VPNPASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # <---  Based on an issue from the git repo for this
      - LOCAL_NETWORK=${LOCALSUBNET}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=${TRANSMSSIONRPCWHITE}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSIONPASSWORD}
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSIONUSERNAME}
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=3           # Change this to be nicer
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true   # Change this to be too nice
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR}/transmission:/data
      - ${SHARED_DIR}:/shared
      - ${DOWNLOADS_DIR}:/data/watch
      - ${DOWNLOADS_DIR}/complete:/data/completed
      - ${DOWNLOADS_DIR}/incomplete:/data/incomplete

  # Downlaod NZBs (usenet)
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    ports:
      - 37012:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/sabnzbd/config:/config
      - ${SHARED_DIR}:/shared
      - ${DOWNLOADS_DIR}/complete:/downloads
      - ${DOWNLOADS_DIR}/incomplete:/incomplete-downloads
      - ${DOWNLOADS_DIR}/watch-files:/watch
      - ${BASE_DIR}/sabnzbd/scripts:/custom-scripts
      - ${LOG_DIR}/sabnzbd:/config/logs
    networks:
      - default

  # Track and automate TV Show downloads for home media
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "37013:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASE_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}/complete:/downloads
      - /mnt/data/TV:/tv
      - ${SHARED_DIR}:/shared
      - ${LOG_DIR}/sonarr:/config/logs

  # Track and automate movie downloads for home media
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "37014:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASE_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}/complete:/downloads
      - /mnt/data/Movies:/movies
      - ${SHARED_DIR}:/shared
      - ${LOG_DIR}/radarr:/config/logs

  
  # Manually search tonnes of usenet indexers at once (if you pay for more than 1)
  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2
    restart: unless-stopped
    ports:
      - "37017:5076"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/hydra:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${SHARED_DIR}:/shared

  # Manually search tonnes of torrent indexers at once
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
       - "37018:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASE_DIR}/jackett:/config
      - ${DOWNLOADS_DIR}/complete:/downloads
      - ${SHARED_DIR}:/shared

  logarr:
    container_name: logarr
    image: monitorr/logarr:develop
    restart: always
    ports:
       - 37009:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/logarr/config:/config
      - ${LOG_DIR}:/var/log/logarrlogs


  #plex:
  #  container_name: plex
  #  image: plexinc/pms-docker
  #  restart: always
  #  volumes:
  #    - ${BASE_DIR}/plex/config:/config
  #    - ${BASE_DIR}/plex/trans:/transcode
  #    - ${MEDIA_DIR}:/media
  #    - ${SHARED_DIR}:/shared
  #  ports:
  #    - "32400:32400/tcp"
  #    - "3005:3005/tcp"
  #    - "8324:8324/tcp"
  #    - "32469:32469/tcp"
  #    - "1900:1900/udp"
  #    - "32410:32410/udp"
  #    - "32412:32412/udp"
  #    - "32413:32413/udp"
  #    - "32414:32414/udp"
  #  environment:
  #    - TZ=${TZ}
  #    - HOSTNAME="Docker Plex"
  #    - PLEX_CLAIM="claim here"
  #    - PLEX_UID=${PUID}
  #    - PLEX_GID=${PGID}
  #    - ADVERTISE_IP="http://ip:32400/"

networks:
  default:
    driver: bridge
