version: "3.7"

services:
  #  Start api.. docker run -dit -p 5000:5000 mavi0/onos-reroute-api:latest
  onos-reroute-api:
    container_name: onos-reroute-api
    image: mavi0/onos-reroute-api:latest
    ports:
      - 5000:5000
