version: "3.7"

services:
  #  Start api.. docker run -dit -p 5000:5000 mavi0/onos-reroute-api:latest
  onos-reroute-api:
    container_name: onos-reroute-api
    image: mavi0/onos-reroute-api:latest
    network_mode: host
    tty: true
    volumes: 
      - /home/arisaie/onos-up/api/json:/reroute/json
    environment:
      - TERM=xterm-256color
